gotcha_password/gotcha_password/urls.py
from django.conf.urls import url

from base.views import *

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^create-account/$', CreateAccountView.as_view(), name='create-account'),
    url(r'^create-account/images/$', CreateImagesView.as_view(), name='create-images'),
    url(r'^create-account/success/$', CreateSuccessView.as_view(), name='create-success'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^login/verify/$', LoginVerifyView.as_view(), name='login-verify'),
    url(r'^login/success/$', LoginSuccessView.as_view(), name='login-success'),
]

gotcha_password/base/models.py
from __future__ import unicode_literals

from django.core import validators
from django.core.files.base import ContentFile
from django.db import models
from django.utils.crypto import constant_time_compare

import time, json
from itertools import permutations

from base.utils import *

class UserManager(models.Manager):
    def create(self, username, email, raw_password, seed, num_images, labels):
        password, salt, permutation = make_password(raw_password, labels)

        user = super(UserManager, self).create(
            username=username,
            email=email,
            password=password,
            salt=salt,
            seed=seed,
            num_images=num_images,
            permutation=','.join(map(str, permutation)),
        )

        # renumber labels so that choosing the same order of labels later
        # will return the correct permutation
        for i, num in enumerate(permutation):
            Label.objects.create(user=user, number=num, text=labels[i])

        return user

# going to use our own User class
class User(models.Model):
    objects = UserManager()

    username = models.CharField(
        max_length=30,
        unique=True,
        help_text='30 characters or fewer. Letters and digits only.',
        validators=[
            validators.RegexValidator(
                r'^\w+$',
                'Enter a valid username. This value may contain only letters and numbers.'
            ),
        ],
        error_messages={
            'unique': 'A user with that username already exists.',
        },
    )
    email = models.EmailField(help_text='Will only be used for communications about this study.')
    # stores just the raw password hashed one time (without salt or permutation)
    password = models.CharField(max_length=128)
    salt = models.CharField(max_length=12)
    # seed for Extract function
    seed = models.CharField(max_length=12)
    # random number of images, from 3 to 7
    num_images = models.PositiveSmallIntegerField()
    # storing permutation for research purposes
    permutation = models.CharField(max_length=50)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.username

    def get_permutation(self):
        return map(int, self.permutation.split(','))

    def set_password(self, raw_password, labels):
        self.password, self.salt, permutation = make_password(raw_password, labels)
        self.permutation = ','.join(map(str, permutation))

        for i, num in enumerate(permutation):
            self.labels.filter(number=num).update(text=labels[i])

    def get_hashed_password(self, iterations=HASH_ITERATIONS):
        permutation = self.get_permutation()
        return hash_password(self.password, self.salt, permutation, iterations)

    def check_password(self, raw_password, permutation):
        """
        Returns True if the given password and the ordered list of labels match the
        stored password hash.
        """
        # in a true implementation, this would list all of the possibilities that are
        # wrong within a certain threshold. instead of allowing wrong images, this
        # will check for exact correctness
        hashed_once = hash_once(raw_password, self.salt)
        hashed = hash_password(hashed_once, self.salt, permutation)
        password = self.get_hashed_password()
        return constant_time_compare(hashed, password)

class Label(models.Model):
    """
    A label for an image sent to the user. User will create labels when they
    create an account and labels will be sent back on log in to match with images.
    """
    class Meta:
        ordering = ['user', 'number']

    user = models.ForeignKey(User, related_name='labels')
    # range [0, user.num_images) representing the order of this label in the list of labels for the user
    number = models.PositiveSmallIntegerField()
    text = models.CharField(max_length=255)

    def __unicode__(self):
        text = self.text
        if len(text) > 13:
            text = '%s...' % text[:10]

        return '%s #%d (%s)' % (self.user.username, self.number, text)

class LoginAttempt(models.Model):
    """
    Model representing each login attempt into the site and various statistics for the login
    attempt. Stores the password resulting from hashing the raw password once and the permutation
    sent for this login attempt.
    """
    user = models.ForeignKey(User, related_name='logins')
    right_password = models.BooleanField()
    correct_images = models.PositiveSmallIntegerField()
    password = models.CharField(max_length=128) # the password the user used to log in again, encrypted
    permutation = models.CharField(max_length=50)
    timestamp = models.DateTimeField(auto_now_add=True)
    # holds results of benchmarking for this login attempt
    benchmarks = models.FileField(upload_to='benchmarks', null=True)

    def __unicode__(self):
        if self.right_password:
            percentage = float(self.correct_images) / self.user.num_images * 100
            text = '%0.1f%%' % percentage
        else:
            text = 'invalid'
        return '%s (%s)' % (self.user.username, text)

    def get_permutation(self):
        return map(int, self.permutation.split(','))

    def get_benchmarks(self):
        return json.loads(self.benchmarks.read())

    def set_benchmarks(self, benchmarks):
        benchmarks = json.dumps(benchmarks)
        filename = '%s_%s.json' % (
            self.user.username, self.timestamp.strftime('%m_%d_%Y_%H:%M:%S')
        )
        self.benchmarks.delete()
        self.benchmarks.save(filename, ContentFile(benchmarks))
        self.save()

    ## TESTING FUNCTIONS

    def check_password_timed(self, threshold, iterations):
        """
        Returns the number of seconds it takes to check if this password is correct, with the
        given parameters.
        """
        salt = self.user.salt
        user_password = self.user.get_hashed_password(iterations)
        start = time.time()

        for p in list_permutations(self.get_permutation(), threshold=threshold):
            hashed = hash_password(self.password, salt, p, iterations=iterations)
            if constant_time_compare(hashed, user_password):
                break

        return time.time() - start

    def crack_permutation(self, threshold, iterations):
        """
        Returns the number of seconds it takes to check every permutation against
        the password, simulating an attacker that knows the password but not the
        permutation.
        """
        salt = self.user.salt
        user_password = self.user.get_hashed_password(iterations)
        start = time.time()

        for permutation in permutations(range(self.user.num_images)):
            success = False

            for p in list_permutations(permutation, threshold=threshold):
                hashed = hash_password(user_password, salt, p, iterations=iterations)
                if constant_time_compare(hashed, user_password):
                    success = True
                    break

            if success:
                break

        return time.time() - start

gotcha_password/base/forms.py
from django import forms

from base.models import User

class PasswordField(forms.CharField):
    def __init__(self, *args, **kwargs):
        kwargs['widget'] = forms.PasswordInput
        super(PasswordField, self).__init__(*args, **kwargs)

class CreateAccountForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    password1 = PasswordField(label='Password')
    password2 = PasswordField(label='Verify password')
    consent = forms.BooleanField()

    @property
    def credential_fields(self):
        return [
            self[field]
            for field in ['username', 'email', 'password1', 'password2']
        ]

    def clean(self):
        cleaned_data = super(CreateAccountForm, self).clean()

        if cleaned_data['password1'] != cleaned_data['password2']:
            raise forms.ValidationError('Passwords do not match.')

        return cleaned_data

class AuthenticationForm(forms.Form):
    username = forms.CharField()
    password = PasswordField()

    def clean_username(self):
        username = self.cleaned_data['username']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError('There is no user with that username.')
        return username

gotcha_password/base/views.py
from django.views.generic import TemplateView, FormView
from django.shortcuts import redirect

from random import randint

from base.forms import *
from base.models import *
from base.utils import *

class HomeView(TemplateView):
    """
    Shows a page that lets users decide if they want to create a new account
    or attempt to log in.
    """
    template_name = 'home.html'

class CreateAccountView(FormView):
    """
    Shows a page that lets a user choose a username and password.
    """
    template_name = 'create_account.html'
    form_class = CreateAccountForm

    def form_valid(self, form):
        """
        Save values in session and redirect to CreateImagesView
        """
        self.request.session['credentials'] = {
            'username': form.cleaned_data['username'],
            'email': form.cleaned_data['email'],
            'raw_password': form.cleaned_data['password1'],
            'seed': get_random_seed(),
            'num_images': randint(3, 7),
        }
        return redirect('create-images')

class CreateImagesView(TemplateView):
    """
    Shows a page with the images for the user to label
    """
    template_name = 'create_images.html'

    def get_context_data(self, **kwargs):
        context = super(CreateImagesView, self).get_context_data(**kwargs)

        credentials = self.request.session['credentials']
        image_seed = extract(credentials['raw_password'], credentials['seed'])
        context['images'] = generate_images(credentials['num_images'], image_seed)

        context['svg_width'] = SVG_WIDTH
        context['svg_height'] = SVG_HEIGHT

        return context

    def post(self, request, *args, **kwargs):
        """
        Accepts the list of labels with the names "label-<num>". The labels have already
        been validated on the client side.
        """
        credentials = self.request.session['credentials']
        labels = extract_labels(request.POST)

        User.objects.create(labels=labels, **credentials)

        return redirect('create-success')

class CreateSuccessView(TemplateView):
    """
    Shows a page informing the user that their account was successfully created.
    """
    template_name = 'create_success.html'

class LoginView(FormView):
    """
    Shows a page that lets the user log in with a given username and password.
    """
    template_name = 'login.html'
    form_class = AuthenticationForm

    def form_valid(self, form):
        self.request.session['credentials'] = form.cleaned_data
        return redirect('login-verify')

class LoginVerifyView(TemplateView):
    """
    Shows a page that displays the images and labels to the user
    """
    template_name = 'login_verify.html'

    def get_context_data(self, **kwargs):
        context = super(LoginVerifyView, self).get_context_data(**kwargs)

        credentials = self.request.session['credentials']
        user = User.objects.get(username=credentials['username'])
        image_seed = extract(credentials['password'], user.seed)
        context['images'] = generate_images(user.num_images, image_seed)
        context['labels'] = Label.objects.filter(user=user)

        context['svg_width'] = SVG_WIDTH
        context['svg_height'] = SVG_HEIGHT

        return context

    def post(self, request, *args, **kwargs):
        """
        Accepts the list of labels with the names "label-<image_num>". Each name is mapped
        to the value of the label, which should match the user's permutation
        """
        credentials = self.request.session['credentials']
        user = User.objects.get(username=credentials['username'])
        labels = map(int, extract_labels(request.POST))

        # typically, here is where authentication would happen. instead of authenticating,
        # show a page with user results and save in a LoginAttempt
        right_password = user.check_password(credentials['password'], labels)
        permutation = user.get_permutation()
        correct_images = sum([
            1 if val == permutation[i] else 0
            for i, val in enumerate(labels)
        ])

        login = LoginAttempt.objects.create(
            user=user,
            right_password=right_password,
            correct_images=correct_images,
            password=hash_once(credentials['password'], user.salt),
            permutation=','.join(map(str, labels)),
        )
        print 'Running benchmarks for %s...' % login
        background_process(run_benchmarks, login, False)

        self.request.session['right_password'] = right_password
        self.request.session['correct_images'] = correct_images

        return redirect('login-success')

class LoginSuccessView(TemplateView):
    """
    Shows a success page that shows the user how many labels they correctly matched
    """
    template_name = 'login_success.html'

    def get_context_data(self, **kwargs):
        context = super(LoginSuccessView, self).get_context_data(**kwargs)

        credentials = self.request.session['credentials']
        user = User.objects.get(username=credentials['username'])
        correct_images = self.request.session['correct_images']

        context['user'] = user
        context['right_password'] = self.request.session['right_password']
        context['correct_images'] = correct_images
        context['num_images'] = user.num_images
        context['percentage'] = '%0.1f' % (float(correct_images) / user.num_images * 100)

        return context

gotcha_password/templates/base.html
{% load staticfiles %}
<html>
<head>
    <title>A Study on Image-Based Password Schemes</title>
    <meta charset="UTF-8">
    <meta property="og:title" content="A Study on Image-Based Password Schemes">
    <meta property="og:description" content="Brandon Chinn's Inquiry 4 assignment for UGIS 188">
    <!--
    <meta property="og:image" content="{% static 'img/fb-logo.jpg' %}">
    <meta property="og:url" content="http://muchmeme-verysurvey.herokuapp.com">
    -->
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <link href="https://fonts.googleapis.com/css?family=Oswald:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=PT+Sans:400,400i,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <script src="{% static 'js/jquery-1.11.2.min.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body>
    <header>
        <h1>A Study on Image-Based Password Schemes</h1>
        <p>UC Berkeley: UGIS 188, Fall 2016</p>
        <p>Brandon Chinn</p>
    </header>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
    <footer>
        <p>Favicon by <a href="https://www.iconfinder.com/designmodo">Designmodo</a>, licensed under CC BY 3.0. Study based on research done by <a href="http://dl.acm.org/citation.cfm?id=2517319">J. Blocki et al (2013)</a>. Full research proposal <a href="{% static 'proposal.pdf' %}">here</a>.</p>
    </footer>
</body>
</html>

gotcha_password/templates/create_account.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/create_account.css' %}">
{% endblock %}

{% block content %}
    <h1>Create an account</h1>
    {% if form.errors %}
        <ul class="errors">
            {% for error in form.errors.values %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {% for field in form.credential_fields %}
            <div class="field {{ field.html_name }}">
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    <p class="help-text">{{ field.help_text }}</p>
                {% endif %}
            </div>
        {% endfor %}
        <div class="field consent">
            <h2>Disclaimer</h2>
            <p class="disclaimer">Usually, passwords are converted ("hashed") multiple times so that it is <a href="https://en.wikipedia.org/wiki/Cryptographic_hash_function">practically impossible to decode</a> when stored on a server. However, in this study, I will be reducing the number of times the passwords are hashed before being stored, so that my data analysis can be done efficiently (methodology and plan for analysis can be found <a href="{% static 'proposal.pdf' %}">here</a>). If you have any questions, please contact me at <a href="mailto:brandonchinn178@gmail.com">brandonchinn178@gmail.com</a>.</p>
            <label for="id_consent">I consent to participating in this study and understand the associated risks:</label>
            {{ form.consent }}
        </div>
        <div class="buttons">
            <button>Submit</button>
            <button class="cancel">Cancel</button>
        </div>
    </form>
{% endblock %}

gotcha_password/templates/create_images.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/create_images.css' %}">
    <script src="{% static 'js/create_images.js' %}"></script>
{% endblock %}

{% block content %}
    <h1>Create an account</h1>
    <p class="explanation">For each image below, provide a descriptive label (the more descriptive the better) that represents that image. The label should be something you'd recognize later for the same image.</p>
    <form method="post">
        {% csrf_token %}
        {% for image in images %}
            <div class="image">
                <svg width="{{ svg_width }}" height="{{ svg_height }}">
                    <rect width="100%" height="100%" fill="#FFF" />
                    {% for ellipse in image %}
                        <ellipse
                            cx="{{ ellipse.x }}"
                            cy="{{ ellipse.y }}"
                            rx="{{ ellipse.width }}"
                            ry="{{ ellipse.height }}"
                            fill="{{ ellipse.color }}"
                            {% if ellipse.is_rotate %}
                                transform="rotate({{ ellipse.rotation }}, {{ ellipse.x }}, {{ ellipse.y }})"
                            {% endif %}
                        />
                    {% endfor %}
                </svg>
                <input name="label-{{ forloop.counter0 }}" autocomplete="off">
            </div>
        {% endfor %}
        <div class="buttons">
            <button class="submit">Submit</button>
            <button class="cancel">Cancel</button>
        </div>
    </form>
{% endblock %}

gotcha_password/templates/create_success.html
{% extends "base.html" %}

{% block content %}
    <h1>Successfully created account</h1>
    <p>Thanks for creating an account! Please come back tomorrow and try to log back in.</p>
    <p><a href="{% url 'home' %}">Back to home</a></p>
{% endblock %}

gotcha_password/templates/email_reminders.html
<p>Hello {{ user.username }}:</p>
<p>You are getting this email because you created an account as part of a study into image-based password schemes. We noticed that you haven't logged back in yet. Please log back in at <a href="http://gotcha-password.herokuapp.com">http://gotcha-password.herokuapp.com</a> to complete your participation.</p>
<p>Thanks,</p>
<p>Brandon Chinn</p>
<p>UC Berkeley, UGIS 188</p>

gotcha_password/templates/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
    <h1>About this project</h1>
    <p>Passwords protect so much of our information, from emails to files on our computers. Yet people still manage to choose <a href="http://www.prweb.com/releases/2012/10/prweb10046001.htm">bad passwords</a>. Even without choosing bad passwords, passwords are flawed in that they often contain dictionary words, which are easier for people to remember. Because of this, text-based passwords usually follow predictable patterns; e.g. there is a high probability that a vowel will follow a consonant, so attackers trying every password combination can eliminate some possibilities.</p>
    <p>In order to alleviate this problem, Jeremiah Blocki and his team developed a password scheme supplementing the usual text passwords with image-based challenges that require constant user interaction. This makes it infeasible to crack passwords using a computer by itself. Their full study can be found <a href="http://dl.acm.org/citation.cfm?id=2517319">here</a>.</p>
    <p>In this study, you will be asked to follow the procedure to create an account using this new password scheme. Then, we ask that you come back tomorrow to attempt to log back in using the credentials you provided.</p>
    <ul class="links">
        <li><a href="{% url 'create-account' %}">Create an account</a></li>
        <li><a href="{% url 'login' %}">Log in to an existing account</a></li>
    </ul>
{% endblock %}

gotcha_password/templates/login.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}
    <h1>Login</h1>
    {% if form.errors %}
        <ul class="errors">
            {% for error in form.errors.values %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="field {{ field.html_name }}">
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}
        <div class="buttons">
            <button>Submit</button>
            <button class="cancel">Cancel</button>
        </div>
    </form>
{% endblock %}

gotcha_password/templates/login_success.html
{% extends "base.html" %}

{% block content %}
    <h1>Authentication results for: {{ user.username }}</h1>
    {% if right_password %}
        <p>You correctly matched {{ correct_images }} out of {{ num_images }} labels to their corresponding picture, which is an accuracy of {{ percentage }}%. On an actual website, your percentage would have to be above a certain threshold to be authenticated. Feel free to try again tomorrow and see if you can do better!</p>
    {% else %}
        <p>Unfortunately, you did not provide the correct password. The images should have looked different than when you first created your account. At this point, you would probably be asked to log in again, if this were an actual authentication website. Feel free to try again later and see if you can get the right password next time!</p>
    {% endif %}
    <p>Thanks for participating in this study!</p>
    <p><a href="{% url 'home' %}">Back to home</a></p>
{% endblock %}

gotcha_password/templates/login_verify.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/login_verify.css' %}">
    <script src="{% static 'js/login_verify.js' %}"></script>
{% endblock %}

{% block content %}
    <h1>Login</h1>
    <p>Select the label you wrote for each image. If you don't recognize any of the images, it might be because you provided the wrong password.</p>
    <form method="post">
        {% csrf_token %}
        {% for image in images %}
            <div class="image">
                <svg width="{{ svg_width }}" height="{{ svg_height }}">
                    <rect width="100%" height="100%" fill="#FFF" />
                    {% for ellipse in image %}
                        <ellipse
                            cx="{{ ellipse.x }}"
                            cy="{{ ellipse.y }}"
                            rx="{{ ellipse.width }}"
                            ry="{{ ellipse.height }}"
                            fill="{{ ellipse.color }}"
                            {% if ellipse.is_rotate %}
                                transform="rotate({{ ellipse.rotation }}, {{ ellipse.x }}, {{ ellipse.y }})"
                            {% endif %}
                        />
                    {% endfor %}
                </svg>
                <div class="labels">
                    {% with i=forloop.counter0 %}
                        {% for label in labels %}
                            <input type="radio" name="label-{{ i }}" value="{{ label.number }}">
                            <div class="label"><label>{{ label.text }}</label></div>
                        {% endfor %}
                    {% endwith %}
                </div>
            </div>
        {% endfor %}
        <div class="buttons">
            <button class="submit">Submit</button>
            <button class="cancel">Cancel</button>
        </div>
    </form>
{% endblock %}

gotcha_password/templates/setup_images.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/setup_images.css' %}">
    <script src="{% static 'js/setup_images.js' %}"></script>
{% endblock %}

{% block content %}
    <h1>Create an account</h1>
    <p>For each image below, provide a descriptive label that represents that image. The label should be something you'd recognize later for the same image.</p>
    <form method="post">
        {% csrf_token %}
        {% for image in images %}
            <div class="image">
                <svg width="{{ svg_width }}" height="{{ svg_height }}">
                    <rect width="100%" height="100%" fill="#FFF" />
                    {% for ellipse in image %}
                        <ellipse
                            cx="{{ ellipse.x }}"
                            cy="{{ ellipse.y }}"
                            rx="{{ ellipse.width }}"
                            ry="{{ ellipse.height }}"
                            fill="{{ ellipse.color }}"
                            {% if ellipse.is_rotate %}
                                transform="rotate({{ ellipse.rotation }}, {{ ellipse.x }}, {{ ellipse.y }})"
                            {% endif %}
                        />
                    {% endfor %}
                </svg>
                <input name="label-{{ forloop.counter0 }}">
            </div>
        {% endfor %}
        <div class="buttons">
            <button class="submit">Submit</button>
            <button class="cancel">Cancel</button>
        </div>
    </form>
{% endblock %}